import React, { useEffect, useState, useCallback } from 'react';
import { Navbar } from '../components/Navbar';
import { StaffManagement } from '../components/StaffManagement';
import type { PosUser } from '../components/StaffManagement';
import axiosClient from '../api/axiosClient';

export default function StaffPage() {
    const [staffList, setStaffList] = useState<PosUser[]>([]);
    const [loading, setLoading] = useState(true);

    const currentUser: PosUser = JSON.parse(localStorage.getItem('user') || '{}');

    const fetchStaffs = useCallback(async () => {
        try {
            setLoading(true);
            const res = await axiosClient.get('/users');
            const data = Array.isArray(res.data) ? res.data : (res.data?.data || []);
            setStaffList(data);
        } catch (error) {
            console.error('Lỗi tải danh sách nhân viên:', error);
        } finally {
            setLoading(false);
        }
    }, []);

    useEffect(() => {
        fetchStaffs();
    }, [fetchStaffs]);

    const handleAddStaff = async (newStaff: PosUser) => {
        try {
            // Tự sinh email ảo nếu không nhập để tránh bị lỗi Unique Email của Backend
            const autoGeneratedEmail = newStaff.email?.trim() ? newStaff.email.trim() : `${newStaff.username.trim()}@pos.local`;

            // BƯỚC 1: Gọi hàm Đăng Ký (Backend chỉ chịu nhận name, username, role)
            const res = await axiosClient.post('/auth/register', {
                username: newStaff.username,
                email: autoGeneratedEmail,
                fullName: newStaff.fullName,
                password: '123', // Pass mặc định
                role: newStaff.role
            });

            // BƯỚC 2: Gọi tiếp hàm Update ngay lập tức để nhồi thêm SĐT, PIN và Quyền hạn vào
            const createdUserId = res.data?.data?.id || res.data?.user?.id || res.data?.id;
            if (createdUserId) {
                await axiosClient.put(`/users/${createdUserId}`, {
                    fullName: newStaff.fullName,
                    email: autoGeneratedEmail,
                    role: newStaff.role,
                    pin: newStaff.pin,
                    phone: newStaff.phone,
                    permissions: newStaff.permissions
                });
            }

            alert('Thêm tài khoản nhân viên thành công!');
            fetchStaffs();
        } catch (error: any) {
            alert(error.response?.data?.message || 'Lỗi khi thêm nhân viên. Tên đăng nhập hoặc Email có thể đã tồn tại!');
        }
    };

    const handleUpdateStaff = async (updatedStaff: PosUser) => {
        try {
            const autoGeneratedEmail = updatedStaff.email?.trim() ? updatedStaff.email.trim() : `${updatedStaff.username.trim()}@pos.local`;

            // Lọc dữ liệu: Chỉ gửi các trường được phép cập nhật để tránh lỗi 400 Bad Request
            const cleanPayload = {
                fullName: updatedStaff.fullName,
                email: autoGeneratedEmail,
                role: updatedStaff.role,
                pin: updatedStaff.pin,
                phone: updatedStaff.phone,
                permissions: updatedStaff.permissions
            };

            await axiosClient.put(`/users/${updatedStaff.id}`, cleanPayload);
            alert('Cập nhật thông tin thành công!');
            fetchStaffs();
        } catch (error: any) {
            alert(error.response?.data?.message || 'Không thể cập nhật thông tin!');
        }
    };

    const handleDeleteStaff = async (staffId: string) => {
        if (!window.confirm('Bạn có chắc chắn muốn xóa nhân viên này khỏi hệ thống?')) return;
        try {
            await axiosClient.delete(`/users/${staffId}`);
            alert('Đã xóa nhân viên khỏi hệ thống!');
            fetchStaffs();
        } catch (error: any) {
            alert(error.response?.data?.message || 'Lỗi khi xóa nhân viên!');
        }
    };

    return (
        <div className="fixed inset-0 flex flex-col w-screen h-[100dvh] bg-[#f0f4f8] font-sans text-slate-900 overflow-hidden overscroll-none select-none">
            <div className="shrink-0 z-20 shadow-sm border-b border-slate-200/60">
                <Navbar />
            </div>

            <main className="flex-1 w-full relative overflow-hidden">
                <div className="absolute inset-0 overflow-auto scrollbar-none overscroll-contain">
                    <div className="max-w-[1400px] mx-auto w-full min-h-full p-4 lg:p-5 flex flex-col">
                        {loading ? (
                            <div className="flex-1 flex flex-col justify-center items-center text-slate-500 font-medium">
                                <div className="w-12 h-12 border-4 border-[#ff7f3f] border-t-transparent rounded-full animate-spin mb-4 shadow-sm"></div>
                                <span className="text-[14px]">Đang đồng bộ dữ liệu nhân sự...</span>
                            </div>
                        ) : (
                            <StaffManagement
                                staffList={staffList}
                                currentUser={currentUser}
                                onAddStaff={handleAddStaff}
                                onUpdateStaff={handleUpdateStaff}
                                onDeleteStaff={handleDeleteStaff}
                            />
                        )}
                    </div>
                </div>
            </main>
        </div>
    );
}